const ALL_PERMISSIONS = [
    "view_patients",
    "create_patient",
    "discharge_patient",
    "record_vitals",
    "record_problems",
    "resolve_problems",
    "record_clinical_updates",
    "record_deterioration",
    "request_investigations",
    "record_investigation_results",
    "review_investigations",
    "manage_tasks",
    "complete_tasks",
    "create_management_plan",
    "create_handover",
    "acknowledge_handover",
    "manage_users",
    "manage_shifts",
    "view_audit",
    "view_reports",
];

const DEFAULT_ROLE_PERMISSIONS = {
    Resident: [
        "view_patients",
        "create_patient",
        "discharge_patient",
        "record_vitals",
        "record_problems",
        "resolve_problems",
        "record_clinical_updates",
        "record_deterioration",
        "request_investigations",
        "record_investigation_results",
        "manage_tasks",
        "complete_tasks",
        "create_handover",
    ],
    Specialist: [
        "view_patients",
        "create_patient",
        "discharge_patient",
        "record_vitals",
        "record_problems",
        "resolve_problems",
        "record_clinical_updates",
        "record_deterioration",
        "request_investigations",
        "record_investigation_results",
        "review_investigations",
        "manage_tasks",
        "complete_tasks",
        "create_management_plan",
        "create_handover",
        "acknowledge_handover",
    ],
    Consultant: [
        "view_patients",
        "create_patient",
        "discharge_patient",
        "record_vitals",
        "record_problems",
        "resolve_problems",
        "record_clinical_updates",
        "record_deterioration",
        "request_investigations",
        "record_investigation_results",
        "review_investigations",
        "manage_tasks",
        "complete_tasks",
        "create_management_plan",
        "create_handover",
        "acknowledge_handover",
    ],
    Admin: [...ALL_PERMISSIONS],
};

module.exports = {
    ALL_PERMISSIONS,
    DEFAULT_ROLE_PERMISSIONS,
};
